---
# setup the default Java implementation via system environment
#- assert: java_implementation in ['oracle', 'openjdk']
#  tags: java

- name: Install Java default implementation
  tags: java
  template:
    src=java.sh.j2
    dest={{ java_install_dir }}/java.sh
    owner=0
    group=0
    mode=0755


- name: Activate Java system environment configuration
  tags: java
  file:
    state=link
    src={{ java_install_dir }}/java.sh
    dest=/etc/profile.d/java.sh

- include: default_Oracle.yml
  when: java_oracle_when

