---

# Setup a custom fact to allow roles depending on Java to configure
#   JAVA_HOME variable
- name: Set JAVA_HOME ansible fact
  tags: java
  set_fact:
    java_home={{ java_install_dir }}/oracle/{{ java_oracle_version_str_pkg }}

- name: Debug
  debug: msg="{{ java_install_dir }}/oracle/{{ java_oracle_version_str_pkg }}/jre/bin/java"
  tags: java

- name: correct java version selected
  alternatives: name=java link=/usr/bin/java path={{ java_install_dir }}/oracle/{{ java_oracle_version_str_pkg }}/jre/bin/java
  tags: java

- name: correct javac version selected
  alternatives: name=javac link=/usr/bin/javac path={{ java_install_dir }}/oracle/{{ java_oracle_version_str_pkg }}/bin/javac
  tags: java


